# Generated by Django 3.1.4 on 2021-01-05 09:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='flavor',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
