# Generated by Django 3.1.4 on 2021-01-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0003_flavor_body'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='flavor',
            managers=[
            ],
        ),
    ]
