# Generated by Django 3.1.4 on 2021-01-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0005_auto_20210117_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
