# Generated by Django 3.1.4 on 2021-01-17 07:55

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0006_auto_20210117_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='title',
            field=models.CharField(max_length=200, validators=[core.validators.validate_code]),
        ),
    ]
