# Generated by Django 3.1.4 on 2021-01-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0007_auto_20210117_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='slug',
            field=models.SlugField(default=False, unique=True),
        ),
    ]
