# Generated by Django 3.1.4 on 2021-01-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0008_flavor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='slug',
            field=models.SlugField(default=False),
        ),
    ]
