# Generated by Django 3.1.4 on 2021-01-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0009_auto_20210119_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavor',
            name='slug',
        ),
    ]
