# Generated by Django 3.1.4 on 2021-03-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientCrawling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('point', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='BoardData',
        ),
    ]
